import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header"
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: {
    template: "%s - GMan's Gaming Lab",
    default: "GMan's Gaming Lab"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-poppins antialiased">
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
